run:
  timeout: 2m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused

output:
  formats:
    - format: colored-line-number

issues:
  exclude-rules:
    # Exclude false positive for yaml import in config
    - path: internal/config/config.go
      text: "undefined: yaml"
      linters:
        - typecheck